apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mynapp-pvc-block
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
