---
- hosts: apache
  become: yes
  vars:
    http_port: 80
    max_client: 200
  remote_user: student
  tasks: 
  - yum:
      name: libsemanage-python
      state: latest
  - seboolean:
      name: httpd_can_network_connect_db
      state: yes
      persistent: yes
  - name: epel repository
    yum: 
      name: epel-release 
      state: latest
  - name: apache is at the latest version
    yum: 
      name: httpd 
      state: latest
    notify:
    - restart apache
  - name: php 7.4 version RPM
    yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm 
      state: latest
  - name: php 7.4 Download
    yum: 
      enablerepo: remi-php74 
      name: php 
      state: present
  - name: php-mysqlnd 7.4 Download
    yum: 
      enablerepo: remi-php74 
      name: php-mysqlnd 
      state: present
  - name: ensure apache is running
    service: 
      name: httpd 
      state: started 
      enabled: yes
  - name: wget Download
    yum: 
      name: wget 
      state: present
  - name: wget url
    get_url: 
      url: https://ko.wordpress.org/latest-ko_KR.tar.gz 
      dest: /tmp/latest-ko_KR.tar.gz
  - name: tar unarchive 
    unarchive: 
      src: /tmp/latest-ko_KR.tar.gz  
      dest: /var/www/html/
      remote_src: yes
      owner: root
      group: root
  - name: wp-config
    copy: 
      src: /var/www/html/wordpress/wp-config-sample.php 
      dest: /var/www/html/wordpress/wp-config.php 
      remote_src: 1
      force: no
  - name: modify wp-config
    replace: 
      path: /var/www/html/wordpress/wp-config.php 
      regexp: database_name_here 
      replace: wordpress_db
  - name: modify wp-config
    replace: 
      dest: /var/www/html/wordpress/wp-config.php 
      regexp: username_here 
      replace: admin
  - name: modify wp-config
    replace: 
      dest: /var/www/html/wordpress/wp-config.php 
      regexp: password_here 
      replace: dkagh1.
  - name: modify wp-config
    replace: 
      dest: /var/www/html/wordpress/wp-config.php 
      regexp: localhost 
      replace: 192.168.122.52
  - name:
    firewalld:
      service: http
      permanent: yes
      state: enabled 
      immediate: yes
  - name:
    service: 
      name: httpd
      state: restarted 
      enabled: true
